name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install uv
      - run: uv sync --dev
      - run: uv run mkdocs build --strict

  publish-docs:
    name: Publish documentation
    needs: docs
    runs-on: ubuntu-latest
    environment: docs

    steps:
      - run: echo 'Publish docs (GitHub Pages, S3, etc.)'

  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest
    environment: release-linux
    env:
      PYINSTALLER_MODULE: saminfo
      PYINSTALLER_NAME: saminfo

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install uv
      - run: uv sync --dev
      - run: test -f "$GITHUB_WORKSPACE/packaging/pyinstaller/linux.spec"
      - run: uv run pyinstaller "$GITHUB_WORKSPACE/packaging/pyinstaller/linux.spec"
        working-directory: ${{ github.workspace }}
      - run: tar -C dist -czf ${PYINSTALLER_NAME}-linux-x64.tar.gz .
      - uses: actions/upload-artifact@v6
        with:
          name: ${{ env.PYINSTALLER_NAME }}-linux-x64
          path: ${{ env.PYINSTALLER_NAME }}-linux-x64.tar.gz


  build-windows:
    name: Build Windows binary
    runs-on: windows-latest
    environment: release-windows
    env:
      PYINSTALLER_MODULE: saminfo
      PYINSTALLER_NAME: saminfo

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install uv
      - run: uv sync --dev
      - run: if (!(Test-Path "$env:GITHUB_WORKSPACE/packaging/pyinstaller/win32.spec")) { throw "spec file not found" }
      - run: uv run pyinstaller "$env:GITHUB_WORKSPACE/packaging/pyinstaller/win32.spec"
        working-directory: ${{ github.workspace }}
      - run: Compress-Archive -Path dist\* -DestinationPath "$env:PYINSTALLER_NAME-windows-x64.zip"
      - uses: actions/upload-artifact@v6
        with:
          name: ${{ env.PYINSTALLER_NAME }}-windows-x64
          path: ${{ env.PYINSTALLER_NAME }}-windows-x64.zip

  release-assets:
    name: Publish release assets
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v6
        with:
          path: release-assets
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*


